# Generated by Django 3.1.4 on 2021-01-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageforcarousel',
            options={'ordering': ['-pk'], 'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
    ]
