# Generated by Django 3.1.4 on 2021-01-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': "страница 'Обо мне'"},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Ссылки на соц. сети'},
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='inst',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='tg',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='vk',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='youtube',
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='текст ссылки'),
        ),
    ]
