# Generated by Django 3.1.4 on 2021-01-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other_page', '0003_auto_20210120_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='inst',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page', to='other_page.social', verbose_name='Истаграм'),
        ),
    ]
