# Generated by Django 3.1.4 on 2021-01-21 13:07

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('other_page', '0004_auto_20210120_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': "страница 'ABOUT ME'"},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'cсылку на соц. сети', 'verbose_name_plural': 'ссылки на соц. сети'},
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='inst',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='background',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='about_me_page/background', verbose_name='фон страницы'),
        ),
        migrations.AddField(
            model_name='social',
            name='page',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='other_page.aboutme', verbose_name='страница'),
        ),
        migrations.AddField(
            model_name='social',
            name='title',
            field=models.CharField(default='', max_length=64, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default='Информация отсутствует...', verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.CharField(default='#', max_length=64, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='текст ссылки'),
        ),
    ]
