# Generated by Django 3.1.4 on 2021-01-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_page', '0005_auto_20210121_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='текст ссылки'),
        ),
        migrations.AlterField(
            model_name='social',
            name='title',
            field=models.CharField(default='', max_length=16, verbose_name='заголовок'),
        ),
    ]
