# Generated by Django 3.1.4 on 2021-01-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20210121_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='uifooter',
            name='background',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='ui/footer-background', verbose_name='задний фон'),
        ),
        migrations.AlterField(
            model_name='uifooter',
            name='email',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='uifooter',
            name='name_dev',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Имя разработчика'),
        ),
        migrations.AlterField(
            model_name='uifooter',
            name='quote',
            field=models.CharField(blank=True, default='', max_length=140, verbose_name='Цитата'),
        ),
        migrations.AlterField(
            model_name='uifooter',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='Телефон'),
        ),
    ]
